tap "adoptopenjdk/openjdk"
tap "cjbassi/ytop"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jetbrains/utils"
tap "koekeishiya/formulae"
tap "localazy/tools"
tap "mongodb/brew"
tap "mykolaharmash/git-jump"
tap "nektos/tap"
tap "rasukarusan/tap"
tap "rigellute/tap"
tap "sambadevi/powerlevel9k"
tap "wix/brew"
brew "atuin"
brew "autoenv"
brew "autojump"
brew "automake"
brew "awscli"
brew "bat"
brew "blueutil"
brew "bzip2"
brew "unbound"
brew "gnutls"
brew "emacs"
brew "cask", link: false
brew "cmake"
brew "cmocka"
brew "ctop"
brew "openldap"
brew "curl"
brew "diskonaut"
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "dos2unix"
brew "doxygen"
brew "dust"
brew "exa"
brew "fnm"
brew "fzf"
brew "gdk-pixbuf"
brew "gh"
brew "git-delta"
brew "git-extras"
brew "git-open"
brew "gnupg"
brew "go"
brew "gobject-introspection"
brew "golangci-lint"
brew "pango"
brew "librsvg"
brew "libtool"
brew "graphviz"
brew "grex"
brew "htop"
brew "makensis"
brew "man2html"
brew "mas"
brew "openjdk"
brew "maven"
brew "mingw-w64"
brew "mockery"
brew "mongosh"
brew "neovim"
brew "node"
brew "openclonk"
brew "openjdk@17"
brew "pinentry-mac"
brew "pre-commit", link: false
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.10", link: false
brew "tcl-tk", link: false
brew "python@3.8", link: false
brew "python@3.9"
brew "starship"
brew "wget"
brew "yarn"
brew "heroku/brew/heroku", link: false
cask "1password-cli"
cask "blackhole-16ch"
cask "blackhole-64ch"
cask "fig"
cask "odrive"
cask "zoom"
mas "EasyRes", id: 688211836
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "Hidden Bar", id: 1452453066
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Outlook", id: 985367838
mas "NordVPN IKE", id: 1116599239
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
